line-length = 88

[lint]
select = ["I"]

[lint.isort]
known-first-party = ["bot", "scripts", "tests"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true
force-sort-within-sections = true