name: Run All Checks Aggregator

on:
  workflow_run:
    workflows:
      - run_all_checks.yml
      - run_all_checks_unix.yml
    types: [completed]

permissions:
  checks: write

jobs:
  aggregate:
    name: Aggregate dispatched run_all_checks results
    runs-on: ubuntu-latest

    steps:
      - name: Write workflow run payload to file
        uses: actions/github-script@v6
        with:
          script: |
            const run = context.payload.workflow_run;
            const fs = require('fs');
            fs.writeFileSync('dispatched_workflow_run.json', JSON.stringify(run, null, 2));

      - name: Create summary check for dispatched run
        uses: actions/github-script@v6
        with:
          script: |
            const run = context.payload.workflow_run;
            const { owner, repo } = context.repo;
            const head_sha = run.head_sha || context.sha;
            const conclusion = run.conclusion || 'unknown';
            const workflow_name = run.name || 'run_all_checks';
            await github.rest.checks.create({
              owner,
              repo,
              name: `run_all_checks/${workflow_name}`,
              head_sha,
              status: 'completed',
              conclusion: conclusion === 'success' ? 'success' : 'failure',
              output: {
                title: `Run All Checks: ${workflow_name} — ${conclusion}`,
                summary: |
                  The dispatched workflow '${workflow_name}' finished with conclusion: ${conclusion}.

                  View the run: ${run.html_url}
              }
            });

      - name: Upload dispatched run payload
        uses: actions/upload-artifact@v4
        with:
          name: dispatched-workflow-run
          path: dispatched_workflow_run.json
          retention-days: 7
