name: Produce coverage for Sonar automatic scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  coverage:
    name: Produce coverage for Sonar automatic scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies and test tools
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt || true; fi
          python -m pip install pytest pytest-cov

      - name: Run tests and generate coverage
        run: |
          # Generate coverage.xml for Sonar automatic scanning
          pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=xml:coverage.xml || true

      - name: Upload coverage artifact for Sonar
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 30

      - name: Notify
        if: always()
        run: echo "Coverage artifact uploaded. Sonar automatic scanning (if enabled) should pick up coverage.xml."
