name: Type Checking

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"

jobs:
  mypy:
    name: MyPy Type Checking
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          allow-prereleases: true

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-mypy-${{ hashFiles('requirements.txt', 'requirements-dev.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-mypy-
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt || echo "⚠️ Some dependencies may not be available for Python ${{ env.PYTHON_VERSION }} yet"
          pip install -r requirements-dev.txt || echo "⚠️ Some dev dependencies may not be available for Python ${{ env.PYTHON_VERSION }} yet"

      - name: Run MyPy type checking (with mypy.ini)
        run: |
          echo "🔍 Running MyPy type checking with permissive mypy.ini configuration..."
          mypy --config-file=mypy.ini bot/ scripts/ || echo "⚠️ Type checking found issues (this is expected with permissive settings)"
        continue-on-error: true

      - name: MyPy report summary
        run: |
          echo "📊 MyPy Type Checking Summary:"
          echo "- Configuration: mypy.ini (permissive defaults)"
          echo "- Python Version: ${{ env.PYTHON_VERSION }}"
          echo "- Target Directories: bot/, scripts/"
          echo "- Status: Completed (errors are non-blocking)"
          echo ""
          echo "ℹ️ Note: This workflow uses permissive mypy settings."
          echo "   Type checking errors are reported but do not fail the build."
          echo "   Settings can be tightened over time as the codebase improves."